version: '3.12'

services:
  #POSTGRESQL DATABASE
  postgres:
    ports:
      - "5432:5432"

  # #POSTGRESQL DATABASE MANAGEMENT TOOL
  # pgadmin:
  #   ports:
  #     - "80:80"

  #FASTAPI BACKEND
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - '.:/code'

  #NEXTJS FRONTEND
  frontend:
    build: ./web/
    ports:
      - "80:3000"
  # #JENKINS PIPELINE WORKFLOW
  # jenkins:
  #   ports:
  #     - 8080:8080
  #     - 50000:50000
