# version: '3.8'

# services:

#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 4321
#       POSTGRES_DB: online_learning_db
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     networks:
#       - backend-network

#   pgadmin:
#     image: dpage/pgadmin4
#     depends_on:
#       - postgres
#     environment:
#       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#       PGADMIN_DEFAULT_PASSWORD: admin
#     networks:
#       - backend-network

#   backend:
#     image: online_learning_image-backend:latest
#     networks:
#       - backend-network

#   frontend:
#     image: online_learning_image-frontend:latest
#     depends_on:
#       - backend
#       - postgres
#     networks:
#       - backend-network

#   jenkins:
#     image: jenkins/jenkins:lts
#     privileged: true
#     user: root
#     environment:
#       - "JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
#     volumes:
#       - /home/ubuntu/jenkins_compose/jenkins_configuration:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock
#       - .:/usr/code
#     networks:
#       - backend-network

# networks:
#   backend-network:
#     driver: bridge

# volumes:
#   postgres-data:
