name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Build Docker Compose Image
        run: docker-compose build 
        # --no-cache --force-rm
      
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Compose Image
        run: docker-compose up -d

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/checkout@v3
      - run: pip install pytest
      - name: Unit Testing
        run: pytest test/test_main.py
    
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      
      - run: docker-compose build backend

      - name: push backend into docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nafizpervez/online_learning_platform:backend
      
      # - uses: actions/checkout@v3

      - run: docker-compose build frontend

      - name: push backend into docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nafizpervez/online_learning_platform:frontend